# Generated by Django 6.0.1 on 2026-01-30 20:43

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politblogApp', '0002_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
    ]
