# Generated by Django 6.0.1 on 2026-01-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politblogApp', '0002_alter_categories_options_remove_categories_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(related_name='news', to='politblogApp.categories', verbose_name='Категории'),
        ),
    ]
