# Generated by Django 6.0.1 on 2026-01-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politblogApp', '0003_remove_news_category_news_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
