# Generated by Django 6.0.1 on 2026-01-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politblogApp', '0004_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='main_project',
            field=models.BooleanField(default=False),
        ),
    ]
