# Generated by Django 6.0.1 on 2026-01-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politblogApp', '0005_categories_main_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='main_project',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
